local funcoffset = 655 -- random

functions =
{
	{
		["name"] = "osc",
		["id"] = 1,
		["arguments"] = {},
		["return_type"] = make_type("sample"),
		["description"] = "Simple oscillator.",
	},
	{
		["name"] = "map_midi_channel",
		["id"] = 2,
		["arguments"] = {make_type("num"), make_type("num")},
		["return_type"] = make_type("void"),
		["description"] = "Map channel to instrument.",
	},
	{
		["name"] = "spectrum",
		["id"] = 3,
		["arguments"] = {},
		["return_type"] = make_const_type("spectrum"),
		["description"] = "Create spectrum.",
	},
	{
		["name"] = "voicepitch",
		["id"] = kOpVoicePitch,
		["arguments"] = {},
		["return_type"] = make_type("num"),
		["description"] = "Returns pitch of the active voice in semitones.",
	},
	{
		["name"] = "voicetime",
		["id"] = kOpVoiceTime,
		["arguments"] = {},
		["return_type"] = make_type("num"),
	},
	{
		["name"] = "voicepos",
		["id"] = kOpVoicePos,
		["arguments"] = {},
		["return_type"] = make_type("num"),
	},
	{
		["name"] = "voiceid",
		["id"] = kOpVoiceId,
		["arguments"] = {},
		["return_type"] = make_type("num"),
	},
	{
		["name"] = "globaltime",
		["id"] = kOpGlobalTime,
		["arguments"] = {},
		["return_type"] = make_type("num"),
	},
	{
		["name"] = "globalpos",
		["id"] = kOpGlobalPos,
		["arguments"] = {},
		["return_type"] = make_type("num"),
	},
	{
		["name"] = "bpm",
		["id"] = kOpBPM,
		["arguments"] = {},
		["return_type"] = make_type("num"),
	},
	{
		["name"] = "bps",
		["id"] = kOpBPS,
		["arguments"] = {},
		["return_type"] = make_type("num"),
	},
	{
		["name"] = "freqToPitch",
		["id"] = kOpFreqToPitch,
		["arguments"] = {make_type("num")},
		["return_type"] = make_type("num"),
	},
	{
		["name"] = "pitchToFreq",
		["id"] = kOpPitchToFreq,
		["arguments"] = {make_type("num")},
		["return_type"] = make_type("num"),
	},
	{
		["name"] = "trunc",
		["id"] = kOpTrunc,
		["arguments"] = {make_type("num")},
		["return_type"] = make_type("num"),
	},
	{
		["name"] = "round",
		["id"] = kOpRound,
		["arguments"] = {make_type("num")},
		["return_type"] = make_type("num"),
	},
	{
		["name"] = "ceil",
		["id"] = kOpCeil,
		["arguments"] = {make_type("num")},
		["return_type"] = make_type("num"),
	},
	{
		["name"] = "floor",
		["id"] = kOpFloor,
		["arguments"] = {make_type("num")},
		["return_type"] = make_type("num"),
	},
	{
		["name"] = "abs",
		["id"] = kOpAbs,
		["arguments"] = {make_type("num")},
		["return_type"] = make_type("num"),
	},
	{
		["name"] = "cos",
		["id"] = kOpCos,
		["arguments"] = {make_type("num")},
		["return_type"] = make_type("num"),
	},
	{
		["name"] = "sin",
		["id"] = kOpSin,
		["arguments"] = {make_type("num")},
		["return_type"] = make_type("num"),
	},
	{
		["name"] = "tan",
		["id"] = kOpTan,
		["arguments"] = {make_type("num")},
		["return_type"] = make_type("num"),
	},
	{
		["name"] = "sqrt",
		["id"] = kOpSqrt,
		["arguments"] = {make_type("num")},
		["return_type"] = make_type("num"),
	},
	{
		["name"] = "log",
		["id"] = kOpLog,
		["arguments"] = {make_type("num")},
		["return_type"] = make_type("num"),
	},
	{
		["name"] = "log2",
		["id"] = kOpLog2,
		["arguments"] = {make_type("num")},
		["return_type"] = make_type("num"),
	},
	{
		["name"] = "log10",
		["id"] = kOpLog10,
		["arguments"] = {make_type("num")},
		["return_type"] = make_type("num"),
	},
	{
		["name"] = "exp",
		["id"] = kOpExp,
		["arguments"] = {make_type("num")},
		["return_type"] = make_type("num"),
	},
	{
		["name"] = "pow",
		["id"] = kOpPow,
		["arguments"] = {make_type("num"), make_type("num")},
		["return_type"] = make_type("num"),
	},
	{
		["name"] = "ADSR",
		["id"] = kOpADSR,
		["arguments"] = {make_type("num"), make_type("num"), make_type("num"), make_type("num")},
		["return_type"] = make_type("num"),
	},
	{
		["name"] = "wavetableosc",
		["id"] = kOpNodeWavetableOsc,
		["arguments"] = { make_type("num"), make_const_type("wavetable") },
		["return_type"] = make_type("sample"),
		["description"] = "Wavetable oscillator.",
	},
}

